import 'package:flutter/material.dart';
import 'package:green_impact/src/generated.dart';

class Questionnaire extends StatelessWidget {
  final Autogenerated questions;

  Questionnaire({required this.questions});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.symmetric(horizontal: 10.0),
      child: Column(
        children: [
          ListTile(
            title: Text('${questions.id} ${questions.title}'),
          )
        ],
      ),
    );
  }
}
