import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:green_impact/auth/repository.dart';
import 'package:green_impact/src/generated.dart';
import 'package:green_impact/src/questionnaire.dart';

class Test extends StatefulWidget {
  @override
  _testState createState() => _testState();
}

class _testState extends State<Test> {
  List<Autogenerated> _question = <Autogenerated>[];

  @override
  void initState() {
    super.initState();
    fetchQuestion().then((value) {
      setState(() {
        _question.addAll(value);
        print(_question.length);
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          child: ListView.builder(
            itemBuilder: (context, index) {
              index == Questionnaire(questions: this._question[index - 1]);
            },
            itemCount: _question.length + 1,
          ),
        ),
      ),
    );
  }
}
