import 'dart:convert';
import 'dart:math';
import 'package:flutter/foundation.dart';
import 'package:green_impact/src/generated.dart';
import 'package:http/http.dart' as http;

var email, token, pwd;

List<Autogenerated> parseProd(String responseBody) {
  var list = json.decode(responseBody) as List<dynamic>;
  var questions = list.map((e) => Autogenerated.fromJson(e)).toList();
  return questions;
}

void setToken(String body) {
  token = body;
}

Future<String> authenticate(String email, String pwd) async {
  try {
    final response = await http.post(
      Uri.parse('https://localhost:5220/api/Authentications/Authenticate'),
      headers: {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*"
      },
      body: jsonEncode({
        'login': email,
        'password': pwd,
      }),
    );
    print(response);
    if (response.statusCode == 200) {
      final Map<String, dynamic> responseData = json.decode(response.body);
      final String token = responseData['jwt'];
      setToken(response.body);
      return response.body;
    } else {
      throw Exception('Failed to authenticate user.');
    }
  } catch (e) {
    print(e);
    throw (Exception(e));
  }
}

Future<List<Autogenerated>> fetchQuestion() async {
  Map<String, String> header = {"Authorization": token};
  final response = await http.post(
      Uri.parse('https://localhost:5220/api/Products/GetAllQuestions'),
      headers: header);

  if (response.statusCode == 200) {
    setToken(response.body);
    return compute(parseProd, response.body);
  } else {
    throw Exception('Failed to authenticate user.');
  }
}
